### ISSUE TITLE
Deleting items from cloud doesn't update the "(#)"

### ISSUE THREAD

**Issue by oathzed** [wako-app/wako#10]
When you delete items from your cloud, the number doesn't get updating on the fly, you have to refresh manually.

![Screenshot_20201215-150530](https://user-images.githubusercontent.com/52545913/102283329-15db6780-3ee7-11eb-85d7-ee5cb44f58a2.png)

**Comment by JumBay** [comment]
This is not done by wako, but by the add-on you're using

**Comment by oathzed** [comment]
> This is not done by wako, but by the add-on you're using

Okay thanks for letting me know 😊
