### ISSUE TITLE
Request: Choose audiostream + subs for Chromecast

### ISSUE THREAD

**Issue by Titula80** [wako-app/wako#103]
Some videos have no audio when casting to Chromecast. 

Can you make it possible to choose audiostream and subtitles (if available) from Chromecast remote? 

Mayble also place the chromecast remote under the same tab as the Kodi remote and show coverart in the background during video playback?

**Comment by JumBay** [comment]
Unfortunately, Chromecast supports only a few media formats (list [here](https://developers.google.com/cast/docs/media)) hence some videos won't play or won't have audio. 
Also, you cannot change the audio stream nor the subtitles, this is the limitation of Chromecast. Kodi is better in this
