### ISSUE TITLE
Lifetime subscription gone

### ISSUE THREAD

**Issue by GrandLupuz** [wako-app/wako#109]
I have paid for a lifetime subscription a while back but the ads are back. What's going on?

**Comment by Kheldan** [comment]
Same issue here

**Comment by JumBay** [comment]
Hi,
Sorry for that, server issue, please clear wako's cache and restart the app, should fixes it

**Comment by Kheldan** [comment]
Résolu!

Merci et beau travail!

David Milette | President & Managing Director
a: SQALogic | <x-apple-data-detectors://0/1> <x-apple-data-detectors://0/1> 235 rue Peel<x-apple-data-detectors://2/1> | Montreal, QC H3C 0P8<x-apple-data-detectors://2/1>
e: david.milette@sqalogic.ca<mailto:david.milette@sqalogic.ca> | w: www.sqalogic.ca<http://www.sqalogic.ca/>
m: + 1 514 402 9967<tel:+%201%20514%20402%209967> | p: + 514 587 8163<tel:+%20514%20587%208163>

This email is confidential, may be protected by professional secrecy and is addressed exclusively to the recipient. It is strictly forbidden for anyone else to broadcast, distribute or reproduce this message. If you received it in error, please immediately destroy it and notify the sender. Thank you.

On Mar 16, 2020, at 8:44 PM, Jean-Baptiste Malatrasi <notifications@github.com> wrote:

﻿

Hi,
Sorry for that, server issue, please clear wako's cache and restart the app, should fix it
