### ISSUE TITLE
Volume Graphic Displays When Switch to Kodi

### ISSUE THREAD

**Issue by jdcookgt1** [wako-app/wako#11]
When I switch to Wako or unlock to Wako, the volume graphic displays on kodi for .1-.2 seconds. Is there a setting I need to change?

**Comment by JumBay** [comment]
That's because your phone syncs its volume to kodi, you can disable this in settings > kodi

**Comment by jdcookgt1** [comment]
I'm on iOS, sorry I didn't state that to start. Turns out it was the link hardware volume button option under configure hosts.
