### ISSUE TITLE
alldebrid /magnet/upload - Magnet is not  valid 

### ISSUE THREAD

**Issue by popcorn2024ok** [wako-app/wako#110]
![IMG_0015](https://github.com/user-attachments/assets/fd57f485-36db-4479-900e-f3ae4018cc19)

Alldebrid stopped working on my iPad Pro the links still don t work for me and I paid for 1 year of Alldebrid. I hope it gets fixed soon Alldevrod in the Wako TV app iOS versions like iPad Pro and iPhone

**Comment by JumBay** [comment]
This is not related to wako but to a 3rd party addon. Plz contact their support
