### ISSUE TITLE
Wako IOS App Instantly Crashes On Launch When On Wifi

### ISSUE THREAD

**Issue by dxfan227** [wako-app/wako#111]
My iOS Wako App crashes immediately on launch if I am on my wifi.....it does not crash when on 4G ( but cant communicate with Kodi this way obv)

Anyone with a similar issue?

**Comment by JumBay** [comment]
Hi
What's your iOS version and wako's one?

**Comment by dxfan227** [comment]
> Hi
> What's your iOS version and wako's one?

Sure
iOS - 13.3.1
Wako - Wako 3.8.0 (build: 2020-03-25)

**Comment by JumBay** [comment]
Ok. Doesn't crash on mine. 
Could you try to remove your Kodi hosts when on 4g and restart wako with wifi on?

**Comment by dxfan227** [comment]
It does not crash when opening, but as soon as I click configure hosts>add it crashes

**Comment by JumBay** [comment]
when on 4g?
If you can join the discord https://discord.gg/3KD8RZ and pm me or on reddit https://www.reddit.com/r/wako/comments/fe5wl8/ui_button_placement/

**Comment by dxfan227** [comment]
discord isn't working for me LOL

Pm'd you on reddit
