### ISSUE TITLE
Have not received lifetime ad removal after donating

### ISSUE THREAD

**Issue by AGithub457** [wako-app/wako#112]
Hi I left a donation to your PayPal a couple days ago of 10€, the current price of that day that needed to get ad free. I still haven’t gotten any notification that I got added to the list, and when I check the same page now it says the minimum is 11€. How to resolve?

**Comment by JumBay** [comment]
Hi,
What's your trakt's username? Please email at wakoapplication@gmail.com with all the information. 
If the contribution has been added, for that to work you have to clear wako's cache in wako > settings and restart the app

**Comment by JumBay** [comment]
It's been fixed
