### ISSUE TITLE
Wako premium 

### ISSUE THREAD

**Issue by jassy7797** [wako-app/wako#112]
Using Wako app on iPad for years, lately it’s registering the auto pay for premium users. Once I’ve selected restore purchases I get an error message 423. Trakt account linked. 
![IMG_0071](https://github.com/user-attachments/assets/54fb3618-356c-4d2a-9e78-67918e0d2009)
![IMG_0070](https://github.com/user-attachments/assets/48f035be-b72c-4d7a-af07-919e5531b2a3)
![IMG_0069](https://github.com/user-attachments/assets/4174543c-d511-4645-882d-15a96687f58a)
![IMG_0068](https://github.com/user-attachments/assets/6becd00b-596d-415b-a277-4bffd12fea7a)
![IMG_0066](https://github.com/user-attachments/assets/63dffa61-5694-44ca-86d7-d1420110e5d0)
![IMG_0065](https://github.com/user-attachments/assets/07b5ca15-147c-485c-b392-bc76a0cca99d)
![IMG_0071](https://github.com/user-attachments/assets/23726856-94dd-47fc-a287-cffaa724235c)
![IMG_0070](https://github.com/user-attachments/assets/e2d97677-eeb0-4f8e-9ee6-f6aba60c3123)
![IMG_0069](https://github.com/user-attachments/assets/912ced25-b35d-41a9-9150-810b5d935738)
![IMG_0068](https://github.com/user-attachments/assets/eed0e27e-d966-4926-bb35-5851f49eeb7d)
![IMG_0065](https://github.com/user-attachments/assets/66d30033-ba08-424e-8f6f-bc8a82d86f67)
![IMG_0064](https://github.com/user-attachments/assets/cf4aa237-de83-4e4f-8de0-989ab24fb743)

**Comment by JumBay** [comment]
Hi your account is locked you should contact trakt
See https://trakt.docs.apiary.io/#introduction/locked-user-account

**Comment by JumBay** [comment]
I'll add a more explicit error message
