### ISSUE TITLE
Movie Scrolling Frozen While Searching

### ISSUE THREAD

**Issue by GittyUpMyHorsey** [wako-app/wako#113]
After hitting the refresh button on the movie page, scrolling becomes broken and no longer works.

I've tried everything including clearing wako cache and force killing the app. The only thing that temporarily works is logging out and then back into my wako account.

**Comment by GittyUpMyHorsey** [comment]
BTW I am using it on the ipad pro m4 ios 18.1 and latest wako app update.

**Comment by GittyUpMyHorsey** [comment]
It almost seems as though it's caused by not having the ad banner at the top anymore on the paid version so it glitches listing the movies as the spacing is different?

Fwiw I have my ipad pro in landscape so I dunno if that's contributing to the problem or not.

**Comment by GittyUpMyHorsey** [comment]
Can someone please take a look at this it's basically making the app unusable for me unless I log out and back in every time I use it.

Thanks!

**Comment by JumBay** [comment]
Hi,
Is it possible for you to screen record the bug and the video here?

**Comment by JumBay** [comment]
Could you check if it's fixed on build: mobile.2024-12-03 -- > Open the app, wait few seconds for the app to update, restart it, then go to wako > settings > scroll down to the bottom and check you have this build.
