### ISSUE TITLE
Alldebrid 'Magnet is not valid' error on iOS app

### ISSUE THREAD

**Issue by datbilling** [wako-app/wako#114]
When trying to open a link using Alldebrid, I get the error 'All Debrid /magnet/upload - Magnet is not valid' on the iOS app.

Also when using 'Add to All Debrid' for a torrent, it says it's been added, but it has not.

Someone on Reddit said that this has been broken since iOS 17? Can this please be fixed now that our debrid options are more limited?

**Comment by JumBay** [comment]
This is related to a third party add-on you have to contact their support.
