### ISSUE TITLE
No Streams Showing Up

### ISSUE THREAD

**Issue by ACEY7773** [wako-app/wako#115]
Hello, I am using wakotv with Helios and RD, no streams are loading. Torrents section shows up streams but none are added to RD.

Error message shows up: “Uncaught error 503 when calling: POST - https//api.real-debris.com/rest/1.0/torrents/selectFiles/“

**Comment by JumBay** [comment]
This is related to a third party add-on you have to contact their support. Also check https://x.com/RealDebrid/status/1859673163681960169
