### ISSUE TITLE
No descriptive text such as release date, runtime info, etc when viewing shows/movies

### ISSUE THREAD

**Issue by broman400** [wako-app/wako#116]
No text such as runtime, release date, etc appear  sometimes

![IMG_2035](https://github.com/user-attachments/assets/fd32d6c9-911e-42d7-a214-c51b3a334517)

https://github.com/user-attachments/assets/e9d94f85-860f-4ea2-86ff-9bd14278822e

Using the latest app on iOS

**Comment by JumBay** [comment]
From your video it seems to load on the 2nd navigation. Is this only for this episode?

**Comment by broman400** [comment]
> From your video it seems to load on the 2nd navigation. Is this only for this episode?

No, it happens pretty frequently for other shows/movies
