### ISSUE TITLE
[Request small edits] Add a dash between show title and Season

### ISSUE THREAD

**Issue by oathzed** [wako-app/wako#116]
![Screenshot_20200501-130629](https://user-images.githubusercontent.com/52545913/80837972-be34f980-8bac-11ea-8298-a72ef7e802e6.png)

Add a dash " - " in between show title and Season for better separation.

**Comment by JumBay** [comment]
I did some changes, but add-ons can create playlists as well and they can set the title they want, wako has no controls this.
