### ISSUE TITLE
[BUG/FiX] On TV show filtering it uses Movie certifications

### ISSUE THREAD

**Issue by oathzed** [wako-app/wako#125]
![Screenshot_20200503-085126](https://user-images.githubusercontent.com/52545913/80918845-d6775680-8d1b-11ea-9dcf-ccc7748af48a.png)

Currently you can't properly search TV certification, no results come up with these certifications even if you leave genre and rating at "All" 

These should be like: TV-PG, TV-14, TV-MA, etc.

This is TV show filtering.

**Comment by JumBay** [comment]
fixed

**Comment by oathzed** [comment]
> fixed

@JumBay I'm on latest 2020-05-17 build and this still hasn't changed for me, has it been pushed yet?

**Comment by JumBay** [comment]
It's on a new binary waiting for approval on stores, but gonna push a new build too

**Comment by oathzed** [comment]
> It's on a new binary waiting for approval on stores, but gonna push a new build too

@JumBay ok gotcha
