### ISSUE TITLE
[BUG] Filtering menu stops working properly

### ISSUE THREAD

**Issue by oathzed** [wako-app/wako#127]
http://imgur.com/a/5YSlyjk

When filtering different stuff, the filtering menu will eventually not work, see video (watched to the end, only about 10 seconds long video)

**Comment by JumBay** [comment]
Do you still have this?

**Comment by oathzed** [comment]
> Do you still have this?

@JumBay Yes it still happens

**Comment by oathzed** [comment]
@JumBay seems to be fixed after latest playstore update :)
