### ISSUE TITLE
Wako on Chromebook

### ISSUE THREAD

**Issue by chrisjf80** [wako-app/wako#129]
Wako will not connect to Trakt. Takes me to Trakt website to authorise wako but quickly switched back to wako & never signs in in Wako. I suspect this is a chromebook problem but just thought I'd ask. Thanks

**Comment by JumBay** [comment]
Yes some else in the past has faced this issue with a chromebook as well.

**Comment by chrisjf80** [comment]
Thanks for reply anyway. Don't really need it on Chromebook. Thanks for the great app.
