### ISSUE TITLE
[Small Bug?] The progress bar for episodes watched caused an issue on the left side

### ISSUE THREAD

**Issue by oathzed** [wako-app/wako#132]
![Screenshot_20200517-205731](https://user-images.githubusercontent.com/52545913/82173205-3ecc4900-9881-11ea-8f4c-430bca750464.png)

The new, progress bar of episodes watched added a blue bar on the side of all the episodes.

Or maybe this is intended? Not sure, seems like an odd choice if so :P.

**Comment by JumBay** [comment]
This is not a progress bar, it's the design
