### ISSUE TITLE
[BUG] Certification showing when not displayed on poster and not on trakt

### ISSUE THREAD

**Issue by oathzed** [wako-app/wako#133]
![Screenshot_20200517-214729~2](https://user-images.githubusercontent.com/52545913/82175858-ee0d1e00-9889-11ea-9de2-3fecce9f863e.png)
![Screenshot_20200517-214734~2](https://user-images.githubusercontent.com/52545913/82175864-f6655900-9889-11ea-8751-cce1052bf60c.png)
![Screenshot_20200517-214821~2](https://user-images.githubusercontent.com/52545913/82175873-fc5b3a00-9889-11ea-83c0-326883fc3640.png)

It also shows "TV-MA" for a Movie, that's a TV certification system I believe. I've seen this on other movies that don't show the certification on the poster also, they don't seem to have certification on trakt so I'm not sure where this certification is coming from.

**Comment by JumBay** [comment]
It's not an issue, trakt doesn't provide the certification information but imdb does

**Comment by oathzed** [comment]
> It's not an issue, trakt doesn't provide the certification information but imdb does

@JumBay Awesome, thanks for the explanation :). Was wondering where it came from lol.
