### ISSUE TITLE
[FIX] Watch trailer inside Browser instead of YouTube app for TV shows 

### ISSUE THREAD

**Issue by oathzed** [wako-app/wako#137]
![Screenshot_20200520-215132~2](https://user-images.githubusercontent.com/52545913/82524657-59eac300-9ae4-11ea-8f63-951cfc5be273.png)

![Screenshot_20200520-215143~2](https://user-images.githubusercontent.com/52545913/82524769-a0402200-9ae4-11ea-9ba6-7c04f0e71042.png)

For some reason when playing a trailer from a TV show it gives you the option to play trailer on your browser instead of the YouTube app, both movie and tv show should use the YouTube app if it's installed on your device, else browser.

**Comment by JumBay** [comment]
This is the normal behavior, there is no youtube trailer for tv show. wako tries to get the trailer from imdb
