### ISSUE TITLE
[FIX] The calendar seems to be off by a day.

### ISSUE THREAD

**Issue by oathzed** [wako-app/wako#138]
![82594754-6d844100-9b59-11ea-878c-ebcacd8279ac~2](https://user-images.githubusercontent.com/52545913/85081190-27ce8e80-b180-11ea-9e8b-dcac48a11d0e.png)

![Screenshot_20200521-114840~2](https://user-images.githubusercontent.com/52545913/82594766-737a2200-9b59-11ea-9116-e9ee93f24193.png)

![Screenshot_20200521-115440](https://user-images.githubusercontent.com/52545913/82595119-edaaa680-9b59-11ea-9905-2fa43d72ec71.png)

Looking at "Homecoming" in my calendar says it's out today, but it's actually out tomorrow (May 22nd) at 12am. Which makes the dates for the last image for the season also wrong.

**Comment by JumBay** [comment]
Do you still get this in the beta?

**Comment by oathzed** [comment]
> Do you still get this in the beta?

It's hard to say since I haven't had any new shows that air at 12 am.

**Comment by oathzed** [comment]
> Do you still get this in the beta?

Actually yes I still get it. Check the show "The Boys" it's ana aMazon show that sits at 12am PST on Fridays. It says the next episode is Friday Sept 18th on the trait website. But on wako in the calendar and on the show page it says September 17th.

**Comment by JumBay** [comment]
Ok I'll check this again, could you tell me your timezones again http://www.timezoneconverter.com/cgi-bin/findzone

**Comment by oathzed** [comment]
> Ok I'll check this again, could you tell me your timezones again http://www.timezoneconverter.com/cgi-bin/findzone

Ok thanks.

Pacific Time - west

**Comment by JumBay** [comment]
I guess that's an issue on trakt.tv website.

I did some test on their website for this episode: https://trakt.tv/shows/the-boys-2019/seasons/2/episodes/5

In trakt settings I played with the timezone option

- For timezone: (GMT-08:00) Pacific Time (US & Canada)
   - AIRS September 18, 2020 12:00 AM on Amazon
- For timezone: (GMT-05:00) Eastern Time (US & Canada)
  - AIRS September 18, 2020 12:00 AM on Amazon
- For timezone: (GMT+01:00) Paris
   - AIRS September 18, 2020 6:00 AM

It seems to work for my timezone but PST and EST should have different time.  
In your case if the EST is right then the episode should airs September 17, 2020 09:00 PM right?

**Comment by oathzed** [comment]
> I guess that's an issue on trakt.tv website.
> 
> I did some test on their website for this episode: https://trakt.tv/shows/the-boys-2019/seasons/2/episodes/5
> 
> In trakt settings I played with the timezone option
> 
> * For timezone: (GMT-08:00) Pacific Time (US & Canada)
>   
>   * AIRS September 18, 2020 12:00 AM on Amazon
> * For timezone: (GMT-05:00) Eastern Time (US & Canada)
>   
>   * AIRS September 18, 2020 12:00 AM on Amazon
> * For timezone: (GMT+01:00) Paris
>   
>   * AIRS September 18, 2020 6:00 AM
> 
> It seems to work for my timezone but PST and EST should have different time.
> In your case if the EST is right then the episode should airs September 17, 2020 09:00 PM right?

Yeah that's weird.. cause the episode does officially air at 12am pst. So yeah eat it should air at 9pm est.

Can you not base the wako internal clock off pst?

**Comment by JumBay** [comment]
wako displays date based on your phone timezeone. 

This is the date trakt returns for this episode: **2020-09-18T04:00:00.000Z** which means 2020-09-18 4am on UTC time so **2020-09-18 12am** on EST and **2020-09-17 9pm** on PST.  

If the date is wrong I cannot do anything.  

You should contact trakt for this.

**Comment by oathzed** [comment]
> wako displays dates based on your phone timezeone.
> 
> This is the date trakt returns for this episode: **2020-09-18T04:00:00.000Z** which means 2020-09-18 4am on UTC time so **2020-09-18 12am** on EST and **2020-09-17 9pm** on PST.
> 
> If the date is wrong I cannot do anything.
> 
> You should contact trakt for this.

Ok I understand. Thanks for debugging it. It does seem wrong, I'll try contacting trakt. Thanks

**Comment by oathzed** [comment]
> I guess that's an issue on trakt.tv website.
> 
> I did some test on their website for this episode: https://trakt.tv/shows/the-boys-2019/seasons/2/episodes/5
> 
> In trakt settings I played with the timezone option
> 
> * For timezone: (GMT-08:00) Pacific Time (US & Canada)
>   
>   * AIRS September 18, 2020 12:00 AM on Amazon
> * For timezone: (GMT-05:00) Eastern Time (US & Canada)
>   
>   * AIRS September 18, 2020 12:00 AM on Amazon
> * For timezone: (GMT+01:00) Paris
>   
>   * AIRS September 18, 2020 6:00 AM
> 
> It seems to work for my timezone but PST and EST should have different time.
> In your case if the EST is right then the episode should airs September 17, 2020 09:00 PM right?

Actually it should air at 3am eastern time if it starts at 12am pacific time. But it says 9PM inside wako.

**Comment by JumBay** [comment]
That's because the date is wrong in trakt.

**Comment by oathzed** [comment]
> That's because the date is wrong in trakt.

Yeah I made a bug report on there site. Waiting to hear back
