### ISSUE TITLE
Stop pausing playback of music when browsing in app

### ISSUE THREAD

**Issue by AGithub457** [wako-app/wako#139]
I never use the Kodi functionality, and use the app for general watch history management and Helios addon. Can we get an option to stop pausing music while we are browsing the movies/tv tabs?

**Comment by JumBay** [comment]
To do this I need to be able to reproduce this.
Can you detail this please?
What's your device iOS or Android?

**Comment by AGithub457** [comment]
iOS 13.5. Any audio source is paused while using the app, especially browsing the tv/movie information. Even if I open Notification Center to press play, it’ll pause again when I go back to the app.

**Comment by JumBay** [comment]
When it does this, are you playing any videos with wako?

**Comment by AGithub457** [comment]
No. And any videos I play through the app happen on VLC, so the app shouldn’t control pause/play anyways.

I don’t use any Kodi functionality, nor the remote.

**Comment by JumBay** [comment]
Ok I'll check it out

**Comment by JumBay** [comment]
In the next version 4.1.3, I did do something for this, but the app will still pause the music on startup. I cannot change this or it disables other features
