### ISSUE TITLE
Option to search multiple categories for manual source select

### ISSUE THREAD

**Issue by onlytanmoy** [wako-app/wako#14]
For 'Search Source manually' pls include option to search **both** Movie and TV Show categories in one go.
I did encounter scenarios where the same file name returned more results under Movie Category than TV Show category.
I have joined both Discord & Telegram channels of Wako, so let me know if you need more details.

**Comment by JumBay** [comment]
This is not wako related anymore but Helios. See https://github.com/wako-unofficial-addons/helios/issues/5
