### ISSUE TITLE
[Feature Request] Add option to browse and play files from Premiumize cloud

### ISSUE THREAD

**Issue by sleepyzor** [wako-app/wako#140]
It would be really great to be able to browse Premiumize/Real Debrid cloud from Wako, and be able to play files on Kodi from there. 
I don't know how hard it would be to implement such a feature, but there are some Kodi addons which allow you to do that, so i'm guessing it shouldn't be too hard.

**Comment by JumBay** [comment]
It's done via Premiumize add-on and other add-on can implement their own API for this too
