### ISSUE TITLE
There is no id from tvdb database for the tv series

### ISSUE THREAD

**Issue by gchmurka123** [wako-app/wako#142]
tvdb ID for tv series is undefined.
Eg. Nomos plugin does not work properly because my video.plugin needs id from tvdb for search mechanism.

For movies, I see the correct ID values for tmdb

**Comment by JumBay** [comment]
I don't understand what you're saying?
Where is there no tvdb ID?
If you've an issue with a third party add-on, please contact their support

**Comment by gchmurka123** [comment]
I think wako passes variable IDs to plugins.
If a plugin should collect id tvdb, please close the case.

**Comment by JumBay** [comment]
Yes it does. But these IDs are given by trakt or simkl now and some IDs could be missing but most of the time they're present.
