### ISSUE TITLE
[BUG] Cloud Files Dont March Trakt

### ISSUE THREAD

**Issue by LN13uLL** [wako-app/wako#147]
![1D55D319-5C0B-44B2-A98C-F99E06B02FC1](https://user-images.githubusercontent.com/67085646/84973639-8e579c00-b0ef-11ea-8ac8-697d5c49fb92.png)
![A131CFF5-7A09-4CDA-9E61-8E2E8645139F](https://user-images.githubusercontent.com/67085646/84973643-90215f80-b0ef-11ea-8949-5a8351ba6f89.png)
![1B3E4767-E552-42D3-A42C-65BA8A183EAC](https://user-images.githubusercontent.com/67085646/84973647-91eb2300-b0ef-11ea-85c5-24980db1e508.png)

Hi when there’s pm cloud files that do not match trakt, the shows are not titled where you can distinguish between episodes. 

It would be nice to either do the following, if wako can’t match up the video files to trakt metadata, it should not try to parse the file or maybe have a toggle to be able to turn off use trakt metadata for file manager.

**Comment by JumBay** [comment]
That's already the actual behavior, but I guess in this case it matches something else. Gonna check this

**Comment by JumBay** [comment]
I did improve the file matching feature and leave the original filename just in case.

**Comment by oathzed** [comment]
@JumBay 

Still have some issues like this. If titles are long like this can you wrap them and maybe make the text smaller so we can see it all? 

![Screenshot_20200618-154255](https://user-images.githubusercontent.com/52545913/85079516-dde3a980-b17b-11ea-9dd9-349f7ff06315.png)
