### ISSUE TITLE
[Fix] Title issue on "Resume" section

### ISSUE THREAD

**Issue by oathzed** [wako-app/wako#149]
![Screenshot_20200618-165044](https://user-images.githubusercontent.com/52545913/85082495-ecce5a00-b183-11ea-9f54-48d779ce502d.png)

Can we get rid of the circled item. This is a playlist of game of thrones, with episode 1-3 and I'm on episode 3 of the playlist so it shows the current one correct but also displays s01e02 after the top title. That doesn't need to be there, just get rid of that part please :).

**Comment by JumBay** [comment]
Is this still present?

**Comment by oathzed** [comment]
I dunno, my add-on isn't creating playlists with more than one item now

**Comment by JumBay** [comment]
Ok if this comes from a third party add-on then you need to see with their support if the issue comes back

**Comment by oathzed** [comment]
This is fixed.
