### ISSUE TITLE
Failed to receive the video URL error

### ISSUE THREAD

**Issue by BrianBirtwell** [wako-app/wako#150]
I am getting a failed to receive video URL message ( the error actually says received ) on every link I try to open on Wali. I have updated to the latest version and only have the official add-ons installed. Running bare Kodi 16. Any help please

**Comment by JumBay** [comment]
You do have this when you open a video from the file explorer?

**Comment by BrianBirtwell** [comment]
> You do have this when you open a video from the file explorer?

It is when I try to open a link from search results in the Wali app. It happens with every link

**Comment by JumBay** [comment]
There is no option in wako to open a link but with file explorer. You're certainly mentioning a third party addon. You have to see with their support
