### ISSUE TITLE
Ads on paid carrion

### ISSUE THREAD

**Issue by jatoprieto** [wako-app/wako#151]
iOS version. 
iOS 14 beta 1 iPhone 11 Pro Max

**Comment by JumBay** [comment]
Did you buy a lifetime contribution or a monthly one? 
Anyway email at wakoapplication@gmail.com with your wako's user ID

**Comment by JumBay** [comment]
Find your user ID and fixed this issue. Sorry for this. If you still see ads, please wako's cache in wako > settings > clear cache and restart the app

**Comment by jatoprieto** [comment]
All set. Thank you!
