### ISSUE TITLE
No streams showing on app, Uncaught error

### ISSUE THREAD

**Issue by markw1983** [wako-app/wako#160]
Hi. Having an issue with the app. Been getting an Uncaught error 400 when calling POST notification coming up. I cannot see any streams, I have uninstalled and reinstalled the app multiple times. I go to use the backup on the account and that's when the issue occurs. Any one got any pointers?

**Comment by JumBay** [comment]
Hi,
I suppose you're using an unofficial add-on since this doesn't exist in wako. In this case please contact the add-on's support to get any help

**Comment by markw1983** [comment]
I'm using Trakt that's the add on I'm using.

**Comment by JumBay** [comment]
No Trakt is part of wako is not an add-on. You can view all installed add-ons in wako > settings > add-ons
