### ISSUE TITLE
Ads are always being shown

### ISSUE THREAD

**Issue by ShinningKnight** [wako-app/wako#162]
Hello Wako TV Support.

I have the latest version of Wako TV App installed onto my Apple device  running the latest Apple iOS. I have recently been having ads repeatedly being promoted even after watch several 30 second long ads I keep getting presented with an ad to watch. This happens each time I select a movie title and then I click on the Netflix or Amazon Video button, which then presents an ad. I watch the ad until it fully ends and then try again, I get another (or the same) ad presented to watch, this continues repeatedly. 

Few days ago there were no issues, after watching two ads I would not be presented with any ads for 24 hour period. I have updated the iOs device with the latest version of Wako TV from the Apple Store, but I still face the same issue.

Please could you help resolve the issue?

Thank You

**Comment by ShinningKnight** [comment]
Hi, 

Thanks for your acknowledgement. Any ideas what might be causing the issue or is there anything you can suggest I can try in the meantime?

Thanks.

**Comment by JumBay** [comment]
I've published a new build `2020-08-18` if you can check it

**Comment by ShinningKnight** [comment]
Many thanks, I have checked App version 4.2.8 (build: 2020-08-18) and issue I reported has now been resolved. 

Thank you!

**Comment by JumBay** [comment]
Great
