### ISSUE TITLE
[BUG] Sometimes episodes don't load from Calendar tab when you press one

### ISSUE THREAD

**Issue by oathzed** [wako-app/wako#163]
See video, Geordie shore doesn't load: 

https://imgur.com/a/ZaryE0i

Edit: it looks like it's not on the episode list in the show: 
![Screenshot_20200818-195514](https://user-images.githubusercontent.com/52545913/90586782-dc8b2900-e18c-11ea-93f7-eea61032b05f.png)

But It is infact on the trakt.tv website itself:

![Screenshot_20200818-195524](https://user-images.githubusercontent.com/52545913/90586830-f167bc80-e18c-11ea-88f4-9222ad9e3230.png)

Edit 2: Looks like when i cleared the cache in the app, the new episodes showed in the tv page. wako should do a check more often and update the tv page more often.

**Comment by JumBay** [comment]
should be fixed now
