### ISSUE TITLE
[Bug] Screen flashes white. Nothing happens. 

### ISSUE THREAD

**Issue by prophet42** [wako-app/wako#166]
Hi. Whenever I click on a show or any button (e.g., configure hosts) the screen flashes white and nothing else happens. It just returns to the screen I was on. I’m on version 4.3.0. I’m also on the latest iOS 14 beta so maybe it is that. It is working for my wife on her iPhone which is on the previous iOS 14 beta. She also has 4.3.0. I’ve tried uninstalling wako and reinstalling. Thanks. Still love wako, by the way.

**Comment by JumBay** [comment]
This a known issue on iOS 14 that apple has fixed and should be fixed in future beta.
