### ISSUE TITLE
[Bug] Ads showing on paid version. 

### ISSUE THREAD

**Issue by jatoprieto** [wako-app/wako#167]
Hello. 
Ads are showing again on my iOS version of the app

**Comment by JumBay** [comment]
Hi,

What's your wako user id ?

**Comment by jatoprieto** [comment]
Jatoprieto

Thanks

**Comment by JumBay** [comment]
Ok, I find an issue on this, it's been fixed. 
Clear wako's cache and restart the app. 

Thanks for the report.
