### ISSUE TITLE
[Edit] make splash screen completely black

### ISSUE THREAD

**Issue by oathzed** [wako-app/wako#168]
So it goes well with the dark theme. You should make the splash screen completely black on android. Currently it's grey.

![Screenshot_20200908-131040](https://user-images.githubusercontent.com/52545913/92523256-e4ab1700-f1d4-11ea-8113-4b512c59ec53.png)

**Comment by JumBay** [comment]
I invite you to test the new version (4.4.0) soon in beta where this is fixed.  
This new version has a lot of changes under the hood so it may contains bugs. 
To join the beta follow this link https://play.google.com/store/apps/details?id=app.wako. The version is currently being review by google, so the link may not work right away but in couple hour it should be ok

**Comment by oathzed** [comment]
> I invite you to test the new version (4.4.0) soon in beta where this is fixed.
> This new version has a lot of changes under the hood so it may contains bugs.
> To join the beta follow this link https://play.google.com/store/apps/details?id=app.wako. The version is currently being review by google, so the link may not work right away but in couple hour it should be ok

Link doesn't have a beta sign up quite yet ;] but really looking forward to trying this out. I'll report back any feedback, thanks for the heads up :]

**Comment by oathzed** [comment]
> I invite you to test the new version (4.4.0) soon in beta where this is fixed.
> This new version has a lot of changes under the hood so it may contains bugs.
> To join the beta follow this link https://play.google.com/store/apps/details?id=app.wako. The version is currently being review by google, so the link may not work right away but in couple hour it should be ok

Just installed the new beta, nice job on the splash screen fix, however when i press the icon to launch the app, there is like a weird pause and then the app will actually open (i know you said there may be bugs, so this could be why)

**Comment by oathzed** [comment]
*closed because fixed in new beta

**Comment by JumBay** [comment]
Ok that's not really visible, but I did some changes in 4.4.1, let me know

**Comment by oathzed** [comment]
> Ok that's not really visible, but I did some changes in 4.4.1, let me know

Still have the same slight delay before the app opens.

It's small, but it's noticable

**Comment by JumBay** [comment]
You do have the 4.4.1? I can say it was noticeable on 4.4.0 but now it's not on my device. 
If you do enable logs in developer option in wako, how long does the app takes to hide the splash screen ?

**Comment by oathzed** [comment]
> You do have the 4.4.1? I can say it was noticeable on 4.4.0 but now it's not on my device.
> If you do enable logs in developer option in wako, how long does the app takes to hide the splash screen ?

Yes I have 4.4.1, it takes the same amount of time to hide the splash screen with dev logs off and on.

Hiding the splash screen isn't the issue.

It's right when you press the app icon to open the app, there is like a second of pause then it opens the app. Still same as 4.4.0

**Comment by JumBay** [comment]
Yes but I'd like to know how long does it takes on your phone cause the splash screen hides itself after a certain amount of time. On my device to takes less than 2sec before being hidden

**Comment by oathzed** [comment]
> Yes but I'd like to know how long does it takes on your phone cause the splash screen hides itself after a certain amount of time. On my device to takes less than 2sec before being hidden

With debug log on and off takes the same time. 1.5 seconds so under 2 seconds.

**Comment by JumBay** [comment]
Could you send me another screen video plz

**Comment by oathzed** [comment]
> Could you send me another screen video plz

Here you go : https://imgur.com/a/PCJXeDe

Notice how "Sync Pro" reddit app opens right away when I press the icon. Wako icon expands slightly then opens with that delay.

**Comment by JumBay** [comment]
On you're talking about the delay when you open the app, not the black screen after the splash screen hides? 
For this unfortunately I cannot do anything right now. Wako is a hybrid app that's why some weird behavior can happen compare to fully native one

**Comment by oathzed** [comment]
> On you're talking about the delay when you open the app, not the black screen after the splash screen hides?
> For this unfortunately I cannot do anything right now. Wako is a hybrid app that's why some weird behavior can happen compare to fully native one

Correct. 

Okay no problem, hopefully one day it can be fixed :).

Cheers man
