### ISSUE TITLE
[BUG] really laggy swipe menu on beta 4.4.6

### ISSUE THREAD

**Issue by oathzed** [wako-app/wako#171]
Seems to happen on "Up next" and "calendar". I know I'm on beta but I just wanted to point out

Video: https://imgur.com/a/sTLl7ch

**Comment by JumBay** [comment]
Good catch, actually it doesn't appear with the beta, I've test an old version and it was also present, gonna check what's going on

**Comment by oathzed** [comment]
> Good catch, actually it doesn't appear with the beta, I've test an old version and it was also present, gonna check what's going on

Sounds good man

**Comment by JumBay** [comment]
Fixed
