### ISSUE TITLE
How many devices is donation valid for? 

### ISSUE THREAD

**Issue by Daniel15** [wako-app/wako#175]
If I donate to remove the ads:
1. How many devices is this valid for? Some apps have a device limit (eg. Tivimate can only be activated on five devices concurrently) but it's unclear what the limits with Wako are
2. Is the license just for devices I own or can I also use it on devices I share with my wife?

Thanks!

**Comment by JumBay** [comment]
Hi,

There is no device limitation. The contribution is linked to your wako's user ID, meaning as long as you're connected to the same user you can enjoy the contribution on all your devices. If you contribute on one device, you may have to clear wako's cache (settings > clear cache) on your other devices to be premium. 

Let me know if it's clearer.

**Comment by Daniel15** [comment]
Thank you! I think this worth documenting in the app somewhere, and on the site :)

**Comment by JumBay** [comment]
I'll add something on the app and Website. I thought the explanation already in the app was clear enough but obviously it's not 😅

**Comment by Daniel15** [comment]
Oh, I missed that text in the app! It does explain it somewhat, but IMO it
should explicitly mention that there's no device limit.

Also I noticed that there's two monthly contribution options: $0.99 and
$1.49. What's the difference between those two?

Thanks!

**Comment by JumBay** [comment]
No difference. You choose what you think the app worths

**Comment by Daniel15** [comment]
Thank you :)
