### ISSUE TITLE
Casting to EUMC

### ISSUE THREAD

**Issue by pdubzzle** [wako-app/wako#177]
Casting with the official Kodi app works wonderfully, but when casted through a fork "EMUC" it doesn't show the movie art or the controls on Lock Screen.

**Comment by JumBay** [comment]
Hi,

Wako kodi built in remote is meant to work on kodi only. What's the advantage of eumc? What's their website?

**Comment by pdubzzle** [comment]
> Hi,
> 
> 
> 
> Wako kodi built in remote is meant to work on kodi only. What's the advantage of eumc? What's their website?

It is kodi it's a modified version of it , let's you buffer and some other options  like linking up real debris and more , you will have to find it on a filelinked or side load it

**Comment by JumBay** [comment]
Sorry this won't be done, only official kodi build is supported. Since wako's sdk is open sourced you're still be able to create a custom add-on to do what you want
