### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by wayoff-dev** [wako-app/wako#179]
I’m wondering why I’m getting permission denied after I’ve paid for the no ads version?

**Comment by JumBay** [comment]
Hi,

Where are you getting this? 
If it comes from an unofficial add-on please contact their support.

**Comment by wayoff-dev** [comment]
Hello

I’m sorry, I meant to mention that the app is showing advertisements on it and still showing that permission is denied.  I donated 16 euros 9/19/2020 to have adds taken off.  I have uninstalled and reinstalled the app and still getting the ads and ‘permission denied’ at the top.

________________________________

**Comment by JumBay** [comment]
What's your wako's username? (wako > settings > contribute you'll find your username).

**Comment by wayoff-dev** [comment]
I was able to login and the ads went away but I am still getting permission denied. My username is: trakt - jojo7674

________________________________

**Comment by wayoff-dev** [comment]
Please just refund my money. I didn’t  use this app for more than a week and I can’t get it to work properly get any good help in trying to get it resolved.

________________________________

**Comment by JumBay** [comment]
Please contact me at wakoapplication@gmail.com with screenshot of the issue I may help you on this.
