### ISSUE TITLE
Trakt Watchlist "Sort By"

### ISSUE THREAD

**Issue by GeneralBison** [wako-app/wako#18]
Currently, I seem to only be able to view my Trakt watchlist in "Rank" order, meaning whenever I add something to the list I have to scroll all the way to the bottom. 
Other lists have a "Sort by" dropdown but the Watchlist does not, could this be added?

I've tried chaning the Default Sorting to Recently Added on the Trakt site but this does not seem to affect the list in Wako.

**Comment by woxie** [comment]
It makes no sense that other lists have it but watchlist does not, is it a bug? @JumBay Would it also be possible to support filters?
![image](https://user-images.githubusercontent.com/33608237/110390793-2144b780-802c-11eb-9cb4-d778f24aad5d.png)

**Comment by JumBay** [comment]
Yeah it's not something provided by trakt's API, it has to be done by the app. I'll see what I can do cause I may not have all information for all the sorting options like trakt could have

**Comment by woxie** [comment]
> Yeah it's not something provided by trakt's API, it has to be done by the app. I'll see what I can do cause I may not have all information for all the sorting options like trakt could have

Isn't it mentioned here? (https://trakt.docs.apiary.io/#reference/sync/get-watchlist/get-watchlist)

Reference: https://github.com/trakt/api-help/issues/58

**Comment by JumBay** [comment]
Well I guess they've updated their API, need to see what did change since my last check months ago.

**Comment by woxie** [comment]
> Well I guess they've updated their API, need to see what did change since my last check months ago.

Thank you for adding this feature to the Movies' watchlist, @JumBay. However, I noticed that the "Sort by" dropdown is still missing from the TV Shows' watchlist. Is this a bug or has it not been implemented yet?

**Comment by GeneralBison** [comment]
What happened with the TV Show sorting? I checked my app and it's not in

**Comment by cojoMan** [comment]
I think the most wanted sort order for my (movies) watchlist - is random, I can definately sort like that in trakt, can we have the random sort order for the brought lists in the app as well ? Thanks.

**Comment by woxie** [comment]
@JumBay Hey, it's been almost a year since this was requested, any updates?

**Comment by JumBay** [comment]
Hi, this has been done for the movie part, but it's more complicated for the shows one.  I'll see what I can do

**Comment by cojoMan** [comment]
@JumBay - I have the same options looking at "my movies watchlist", and "my tv shows list", sorting options which are default/rank/recently added/release date. Are there supposed to be more sorting options on the movies you mean ?
