### ISSUE TITLE
Can I install Wako on my same Nvidia Shield (2017) as I have Kodi?

### ISSUE THREAD

**Issue by SchmyeBubbula** [wako-app/wako#181]
Can I install Wako on my same Nvidia Shield (2017) as I have Kodi?
I don't have a smartphone.
I need a download link — Google Play won't install it, neither will Aptoide TV, and APKTime doesn't find it.
If Wako in principle will work with Kodi on the same device, would that mean that the Kodi setting, "Allow remote control from applications on OTHER systems" needn't be enabled?

**Comment by JumBay** [comment]
1. wako is not meant to be used on android tv, it could work but it's not optimised for.
2. Yes you have to enable Allow remote control from applications on OTHER systems
