### ISSUE TITLE
[Bug] Search requires the exact string

### ISSUE THREAD

**Issue by woxie** [wako-app/wako#183]
Searching for a movie or TV show requires the user to input the exact title rather than the first few characters contained within a word of said title.

Here are some examples:
<img src="https://user-images.githubusercontent.com/33608237/95736722-34558600-0c4c-11eb-9169-aa2adaacfc26.PNG" width="360">
<img src="https://user-images.githubusercontent.com/33608237/95736738-3881a380-0c4c-11eb-8835-38972392b395.PNG" width="360">
<img src="https://user-images.githubusercontent.com/33608237/95736757-3fa8b180-0c4c-11eb-9a14-929b59d8b19b.PNG" width="360">
<img src="https://user-images.githubusercontent.com/33608237/95736766-42a3a200-0c4c-11eb-8603-30b772f317cf.PNG" width="360">

Thank you in advance 👍

**Comment by JumBay** [comment]
Hi,

This is a trakt.tv issue. You should open an issue on [their github](https://github.com/trakt/api-help/issues). 

This is the API call that is made:
> https://api.trakt.tv/search/movie?query=big+buc&extended=full&page=1&limit=20&movie=title

As you can see it doesn't return any result, but if you type the full movie name it works : 
> https://api.trakt.tv/search/movie?query=big+buck&extended=full&page=1&limit=20&movie=title
