### ISSUE TITLE
NaN between S01e01 and episode title

### ISSUE THREAD

**Issue by Minefield247** [wako-app/wako#188]
I'm getting the letters NaN between the season and episode number and the episode name in the episode view.

**Comment by JumBay** [comment]
Could you show me a screenshot please?

**Comment by Minefield247** [comment]
![Screenshot_20201025-115226](https://user-images.githubusercontent.com/34307802/97115758-6e189900-16f0-11eb-99bb-0b6ad9e4be5e.jpg)

**Comment by Minefield247** [comment]
Attached

**Comment by JumBay** [comment]
will be fixed in next release

**Comment by Minefield247** [comment]
Thanks
