### ISSUE TITLE
TV Series YouTube trailer

### ISSUE THREAD

**Issue by Cizzzzz** [wako-app/wako#190]
Hi, It seems that the YouTube trailer button is never working for TV series. Always 'No trailer found'. 
Thanks for the good work.

**Comment by JumBay** [comment]
Hi,

Do you have an example? I did test a few and I always get a trailer.

**Comment by Cizzzzz** [comment]
Sure. Here a video showing ‘no trailer’ on tv series. 

https://drive.google.com/file/d/1EpxJ0V5aTOuzGxDb6AnhaqoqtpDaqFPB/view?usp=drivesdk

Thanks!

**Comment by JumBay** [comment]
If you do wait until the imdb rating appears, does the trailer load?

**Comment by Cizzzzz** [comment]
No. Even after the IMDB rating is showing for 15 secs, still no trailer.

**Comment by JumBay** [comment]
Ok I can confirm it's not working on an iphone but it does on android, gonna check this

**Comment by JumBay** [comment]
I did see the issue yesterday on an iphone, but today it works. is it the same for you?

**Comment by Cizzzzz** [comment]
Unfortunately still not. Strange.

**Comment by JumBay** [comment]
If you click on the IMDb rating, it should open imdb website, on this website could you see trailers?

**Comment by Cizzzzz** [comment]
Yes. Via IMDB works fine. Can be a good work around for now.  Thanks for your time you are putting in this. 🙂

**Comment by JumBay** [comment]
Should be fixed in 4.6.9

**Comment by Cizzzzz** [comment]
Thanks a lot. It works. Keep up the great work!
