### ISSUE TITLE
Pop up menus don't go away on back press

### ISSUE THREAD

**Issue by oathzed** [wako-app/wako#195]
Check video:

https://imgur.com/a/Rvmurm9

For any of these pop up menus, when you press back it should stay on the page you're on but get rid of the pop up menu.

This menu also has the same issue:
![Screenshot_20201103-182559](https://user-images.githubusercontent.com/52545913/98062042-1b329600-1e02-11eb-8bf0-0ff0c92ba618.png)

**Comment by oathzed** [comment]
Was this menu not possible to do? @JumBay :o

![Uploading Screenshot_20201104-225850.png…]()

**Comment by JumBay** [comment]
Yes I didn't check that one.
