### ISSUE TITLE
Incorrect airing time

### ISSUE THREAD

**Issue by oathzed** [wako-app/wako#199]
Says 2am in wako but on trakt it comes out at 9pm pst

![PXL_20201110_204807426~2](https://user-images.githubusercontent.com/52545913/98732155-a1476300-2353-11eb-87de-952ece6c8c1c.jpg)
![Screenshot_20201110-124753~2](https://user-images.githubusercontent.com/52545913/98732216-b3c19c80-2353-11eb-91e5-9c541b59bbe2.png)

**Comment by JumBay** [comment]
Is the date correct in the calendar?

**Comment by oathzed** [comment]
> Is the date correct in the calendar?

It says 6pm in the calendar

**Comment by JumBay** [comment]
weird it's the same date parser that's used

**Comment by oathzed** [comment]
> weird it's the same date parser that's used

Yeah that's weird :/

**Comment by oathzed** [comment]
> weird it's the same date parser that's used

Seems fixed now, updated to latest wako and cleared cache. Trakt was having issues today so maybe that was it?
