### ISSUE TITLE
Clicking on movies sometimes get spinning wheel

### ISSUE THREAD

**Issue by mrXoo** [wako-app/wako#2]
Clicking on movies sometimes get spinning wheel   The only way I can get movies back is to restart the app.

**Comment by JumBay** [comment]
Hi,

Do you have an example or it's random?

**Comment by mrXoo** [comment]
It’s very random. Did it for me last night and also my friend had it happen on his. Both iPhone.

**Comment by JumBay** [comment]
I've published a new release (in review, should be available soon) 4.7.7 let me know if you still encounter the issue

**Comment by mrXoo** [comment]
Will do thanks.

**Comment by JumBay** [comment]
The version has been approved by Apple, you can check now

**Comment by mrXoo** [comment]
Thanks I will try.
