### ISSUE TITLE
Weird Kodi host problem

### ISSUE THREAD

**Issue by Minefield247** [wako-app/wako#200]
Up until a couple of weeks ago my kodi select add-on was working perfectly. I would select the media I wanted to play, it would prompt me for which host I wanted, then it would play the media on that host.
But lately things have been strange. Below is a breakdown or exactly what is happening, to save any confusion, I am going to call my hosts 'firestick' and 'shield'.

1. The Wako app is focused on the shield. I select the media I want to play, it prompts me for my host, I select 'shield' the media plays on my shield. Perfect.
2. With the wako app still focused on the shield. I select the media I want to play, it prompts me for my host, I select 'firestick', however the media starts playing on my shield but my Waco app focuses on the fire stick.
3. With the Waco app now focused on the firestick. I re select the media I want to play, it again prompts me for my host, I select firestick again and the media plays on my firestick (as well as my last selection that's still playing on my shield).

It appears as though wako/Kodi Select is sending the play command before switching the host, instead of after.

Wako Version 4.7.2
Kodi Select version 1.0.0

It maybe just me but thought I'd bring it up. If you need anymore information let me know.

**Comment by JumBay** [comment]
If you don't use `kodi select` but you switch host from the remote control do you still encounter the issue? I'll have a look on the add-on to see if there is something that's been broke recently

**Comment by Minefield247** [comment]
If I switch hosts manually (i.e. in the setting menu) the media plays on the new host as requested. It definitely seems to be something with the auto host switching.

**Comment by JumBay** [comment]
would be fixed in 4.7.3

**Comment by Minefield247** [comment]
Thanks
