### ISSUE TITLE
Not able to Restore Purchase after Phone Reset

### ISSUE THREAD

**Issue by prime3x** [wako-app/wako#22]
I made a lifetime contribution to Tier 1 back in 2020 and after resetting my phone, I am unable to restore my purchase. Clicking the restore purchase button do nothing. Any help?

**Comment by JumBay** [comment]
Are you connected to your trakt account?

**Comment by prime3x** [comment]
No! still not

**Comment by JumBay** [comment]
send me your wako's user name present in the contribution page at wakoappalication@gmail.com or here if you don't mind to share it

**Comment by prime3x** [comment]
Is it my Gmail address which I use on my Andriod phone? I don't know how to find the user name on Wako. I have the purchase receipt from Google as well.

**Comment by JumBay** [comment]
it's in wako > settings > contribution, you'll see it at the top of the page (you have to connect wako to trakt or simkl first)

**Comment by prime3x** [comment]
simkl-4656837 that's my ID

**Comment by prime3x** [comment]
connecting to Trackt restored my subscription. Thank you for your help

**Comment by JumBay** [comment]
Great, enjoy
