### ISSUE TITLE
kodi v19 matrix requires login credentials

### ISSUE THREAD

**Issue by npmstart-pray** [wako-app/wako#23]
this is preventing an automatic sync/connection.  wako needs updating to reflect this.

**Comment by JumBay** [comment]
The document have been updated for this, but the app can still auto detect your kodi, but you have to set credentials. What kind of update you have in mind?

**Comment by npmstart-pray** [comment]
Actually, it can only detect kodi if my htpc is named kodi. My htpc running kodi has a different network identifier. Allow me to input that into wako so they can talk and I’ll be happy.

**Comment by npmstart-pray** [comment]
Marking issue as closed, as this has been resolved with a recent update. Thank you
