### ISSUE TITLE
Hide TV shows without unwached episodes.

### ISSUE THREAD

**Issue by rebelone** [wako-app/wako#24]
In the section 'My TV Shows' the following option whould be very welcome. 

Hide shows that do **not** have any unwached episodes.

This way it only TV shows left to watch are visible and all the unrelevant clutter is hidden. 
When a new episode is aired the show in question should show-up again.

**Comment by JumBay** [comment]
I could add a filter for that but that’s exactly what up next to watch does on the home page, isn’t it?

**Comment by rebelone** [comment]
Well.. Not really.
'Up Next' does not have that (very handy) new episode indicator that shows how many unwached episodes are left of a particular show, and the TV show tab does. So this section is great for benge watching. 

Also for me, there is stuff missing al the time in 'Up Next' that does appears in 'My TV Shows', so I always check 'My TV Shows. 

A filter is very welcome to me here. Why see stuff that is already watched, that should be in a history section in my opinion.
Something just like that hidden toggle will do just fine.

**Comment by JumBay** [comment]
If you see video that are marked as watched then it's an issue. Keep in mind, for performance reason, if  you mark something as watched out of wako you may notice a 15min delay before seeing this in wako
