### ISSUE TITLE
App crashes if media is started first on kodi 19

### ISSUE THREAD

**Issue by CatharsysAmaeth** [wako-app/wako#24]
iOS 14.3 user. 
Remote box running corelec kodi19 (with user and password setup)

if I open the app while media is playing wako crashes. (Media started via hdmi-cec remote). If I stop the media the app runs fine.

if I start media from app it does not crash.
If I close the app while media is running and remove it from memory app crashes 

this does not happen on kodi18 and also tested with and without jailbreak. Same behaviour.

app version 4.8.6

**Comment by JumBay** [comment]
Hi,
I'm trying to reproduce the issue with no luck.

Could you try this: 
1. From wako's remote control, open this link: https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4 (on the remote on the left of the up arrow you have a button to open a link). Does the app crash?
2. Kill the app but don't stop the video, reopen the app, does it crash?
3. Do you have another iOS with the same issue?

**Comment by CatharsysAmaeth** [comment]
1. App does not crash
2. App does not crash 
3. Yes. iOS 13.3 haves same behaviour. If I start media directly on kodi and after open wako while it’s playing it crashes. As soon as I press stop it no longer crashes. 

If I press play on Lodi and If I put my mobile in airplane mode I can open the app(as expected) then if I disable airplane mode and press first tab it crashes

**Comment by JumBay** [comment]
What I've tried so far without any issue: 
- Install the latest kodi version (19.1) on my laptop
- download the video from the link above
- open this video in kodi from its file explorer
- open wako on an ios device
- no crash

Could you try to reproduce these steps and let me know what happens?  I guess you use an add-on in kodi to open videos that might be the origin of the crash.

**Comment by CatharsysAmaeth** [comment]
You are on to something.

It is kodi add-on related.
I tested with kodi 19.2 and with Latest Seren and Latest Venom it crashes. But with latest TheOath it does not crash. 
the odd part is that Venom and TheOath are both Exodus forks.

I will try later today your test

**Comment by CatharsysAmaeth** [comment]
Tried your steps : 
open the video in kodi from its file explorer
open wako on an ios device no crash also.
so it is kodi addon related as you suspected.

**Comment by JumBay** [comment]
Do you encounter this issue on kodi 19.1 not 19.2?

**Comment by CatharsysAmaeth** [comment]
Sorry I wasn’t that clear. At first I tested with 19.2 and then rolled back to 19.1 to do your requested tests. So I tested with both having the same behaviour.

**Comment by JumBay** [comment]
Hum, I'm not able to reproduce this on an iPhone 6s with the latest iOS version, it's hard to debug without that

**Comment by CatharsysAmaeth** [comment]
How can I help to debug further ? 
(Forgot to mention that I’m a lifetime contributer) 
Maybe you can provide a TestFlight version with some kind of debug? 
Let me know how can I help

**Comment by CatharsysAmaeth** [comment]
Rare issue that is fixed on kodi 19.2 later tree

**Comment by JumBay** [comment]
Great.
Enjoy
