### ISSUE TITLE
BUG: Movies cant be managed to a custom trakt list. They are just not added

### ISSUE THREAD

**Issue by Animizio** [wako-app/wako#26]
like said in the title, movies cant be added to custom trakt lists. it says its added but after checking the custom list its not there or just checked the movie again and its not able to get "removed", it still shows to add it. trakt website shows that its really not added the list. there must be a bug with movie adding, tv shows are working fine.

**Comment by JumBay** [comment]
This could be a trakt issue. Can you manage to add them from trakt's website? If so could you provide some examples to try it out?

**Comment by Animizio** [comment]
Yeah adding from Trakt works fine.

**Comment by JumBay** [comment]
I cannot reproduce the issue, if you try to do it on a new list do you still encounter the issue? If so, could you give your trakt user ID here or on discord, email: wakoapplication@gmail.com.

Thanks

**Comment by Animizio** [comment]
Well it's definitely the android app. It's working on ios, not on Android.

**Comment by JumBay** [comment]
What's your android version? Could you try to update Android Webview from the playstore and see if it fxes something? I'm using android as well withtout any issue

**Comment by Animizio** [comment]
I'm using android version 10.
Sadly there are no updates, I always keep everything up to date.
When I add,I get the message it got added.
But after checking its not there and I could add it again and again.

**Comment by JumBay** [comment]
Did you try with another list?
