### ISSUE TITLE
Top Part Not Clickable on IOS 14 iPhone 12

### ISSUE THREAD

**Issue by Animizio** [wako-app/wako#27]
I Cant Click anything in the top Part of the wako App from the iPhone 12 pro Max with iOS 14. the refresh Button, the search bar, etc.
Nothing can be clicked on the top part. It happens on every screen

**Comment by JumBay** [comment]
Are you a premium user? Cause I'm wondering if for any reason the ads banner, which is on top of the app, is not visible but over the content and block you to click on the content underneath it. I'm gonna check this anyway

**Comment by Animizio** [comment]
No I don't have premium yet. Maybe it happens because pihole, so he does not show the ad but it's also not clickable. So it's an invisible ad and bugs the app.

**Comment by Animizio** [comment]
Yes, when I don't use pihole, the ad is there and the stuff is going down.
Without the ad the stuff is on top and is not clickable there.

**Comment by JumBay** [comment]
I'm waiting for apple to approve a new version, then if you could try it (I'll send you the testflight link). Send me your wako's user ID I'll make you premium.

**Comment by JumBay** [comment]
I'm waiting for apple to approve a new version, then if you could try it (I'll send you the testflight link). Send me your wako's user ID I'll make you premium.

**Comment by Animizio** [comment]
Sure I will test it.

Thanks, my wako ID is trakt-aniplex
