### ISSUE TITLE
Shoes missing in up next to watch

### ISSUE THREAD

**Issue by adz013** [wako-app/wako#28]
Installed the app yesterday and love it, but have a little issue, some of my shows don't show up in up next to watch in the home tab but they show unwatched episodes in the TV shows tab
![Screenshot_20190518_093531_app wako](https://user-images.githubusercontent.com/50766995/57967251-5a420280-7954-11e9-93ef-e8fc960b0d5e.jpg)
![Screenshot_20190518_093506_app wako](https://user-images.githubusercontent.com/50766995/57967254-60d07a00-7954-11e9-860e-b4bd4d8a955b.jpg)

**Comment by codenamerhubarb** [comment]
I have the same issue, except with my shows, not shoes :)
Using android app 2.2.5 on a Samsung galaxy s9.

**Comment by codenamerhubarb** [comment]
My mistake. There were some season 0 specials I hadn't marked as watched. Once I marked season 0 as watched and restarted the app it now shows up in the list on the home page.
