### ISSUE TITLE
Gap between 1st and 2nd columns (iPad)

### ISSUE THREAD

**Issue by somexone** [wako-app/wako#3]
Hi there,

I am not sure if you're already aware of this bug but on my iPad when you go to movies you can notice there's a gap between the 1st and 2nd columns. The TV shows section has the exact same issue and it's also present in landscape mode on both as well. 

I've attached screenshots of both portrait and landscape to help you better understand. These are only of the movies section but TV shows has the same problem as well. 

Thank you. 

![image](https://user-images.githubusercontent.com/75576429/101284370-466e2380-37ba-11eb-8cc9-dd8ad95945c5.jpeg)

![image](https://user-images.githubusercontent.com/75576429/101284376-4a9a4100-37ba-11eb-9b87-5422275a9ca1.jpeg)

**Comment by JumBay** [comment]
Thanks for the report, I'm gonna see what's going on.

**Comment by somexone** [comment]
Thank you for looking into it. I'm really enjoying your app so far and would really appreciate this issue fixed cause it's killing my OCD haha. 

I'd even throw in another tip for you! 😃

**Comment by JumBay** [comment]
It's been fixed in 4.7.8

**Comment by somexone** [comment]
Thanks dude. You're the best!
