### ISSUE TITLE
REQUEST: support for ratings from rotten tomatoes, metacritic etc via OMDB api

### ISSUE THREAD

**Issue by chiefkes** [wako-app/wako#32]
http://www.omdbapi.com/

OMDB API is already being used in many kodi skins to provide this data.

Additionally would be nice to have links to the rotten tomato and metacritic pages alongside the IMDB link.

**Comment by JumBay** [comment]
There is now an add-on for this made a third party dev
https://raw.githubusercontent.com/s7m/oola-wako-addon/master/dist/manifest.json
