### ISSUE TITLE
REQUEST: add to custom trakt list

### ISSUE THREAD

**Issue by Animizio** [wako-app/wako#37]
At the moment there is only the option to add movies to watchlist or collection. Would be nice to be able to add both TV shows and Movies to custom trakt lists. Very useful, if more than one list are used.

**Comment by akuiraz86** [comment]
+1

**Comment by icpryde** [comment]
This is what I'm waiting for and would be amazing!

**Comment by JumBay** [comment]
done in v3.1.0

**Comment by Animizio** [comment]
Please reopen. I can only use 1 of my 2 lists there for adding and removing.
For all the other stuff I can see both lists.

**Comment by JumBay** [comment]
could you please tell me your trakt username plz and tell which list you should see and what you're really seeing. Thx

**Comment by Animizio** [comment]
Trakt Username:
Daniel's watchlist (not working)
Jacquelines watch list (working)
