### ISSUE TITLE
[HELP] Trakt sync via kodi depeding on where you start your stream

### ISSUE THREAD

**Issue by cojoMan** [wako-app/wako#37]
Using this app and sending links found via helios to a kodi setup, trakt sync recognizes them and I see the message from the scrobbling start. If I stop, they restart the stream, but this time from the "my files"/explorer section, for the same stream - for some reason scrobbling does not trigger. Not sure why.

**Comment by JumBay** [comment]
First no support for unofficial add-ons, because there're not developed by wako.
The explorer feature will try to identify the videos from their filename which is not a perfect solution.
