### ISSUE TITLE
 REQUEST: German language for titles & description

### ISSUE THREAD

**Issue by Animizio** [wako-app/wako#38]
It would be very nice, if we can change the Language of the titles and descriptions to german.

**Comment by JumBay** [comment]
To do so, I'll have to support the German language, could you translate this: https://github.com/JumBay/wako/blob/master/i18n/en.json. Just translate into German all the English part after `:`, don't translate the key. See how this is done for French: https://github.com/JumBay/wako/blob/master/i18n/fr.json
Thanks

**Comment by Animizio** [comment]
Already working on it :)

**Comment by geldorph** [comment]
I'm going to do the same for Dutch

**Comment by JumBay** [comment]
If you're  not in a rush, I'll advise you to wait for the next release, the files will be modified

**Comment by JumBay** [comment]
Any progress on it?

**Comment by Animizio** [comment]
I did it for a very old version and lost it some time ago. If anyone want to do it, go on. I'm too busy with Kodi projects atm, sorry.
