### ISSUE TITLE
Request to use custom paste in URL

### ISSUE THREAD

**Issue by eddavidson** [wako-app/wako#42]
I’ve created a custom players list and am wanting to import it. 
It’s saying to check the URL

**Comment by JumBay** [comment]
What’s your url?

**Comment by eddavidson** [comment]
https://pastebin.com/raw/kT3RP2tF

I’m just trying to figure out how the players work

**Comment by JumBay** [comment]
It depends on how plugins work. 
These are the variable you can use in your URLs and will be replaced by the correct value:
```ts
interface MediaReplacement {
  tmdbId: number;
  rating: number;
  date: string;
  title: string;
  tagline: string;
  plot: string;
  original_title: string;
  imdb: string;
  year: number;
  duration: number;
  mpaa: string;
  genres: string;
  fanart: string;
  poster: string;
  id: number;
  slug: string;
  trakt: number;
  showTmdbId: number;
  seasonNumber: number;
  episodeNumber: number;
  'title_+': string;
  tvdb: number;
  season: number;
  episode: number;
  'clearname_+': string;
  firstaired: string;
  'plot_+': string;
  thumbnail: string;
  now: string;
  banner: string;
  epimdb: string;
  eptmdb: number;
  eptrakt: number;
  epid: number;
  network_clean: string;
  clearname: string;
  epyear: number;
  tmdb: number;
  episodes: number;
  seasons: number;
  series_firstaired: string;
  seasons_no_specials: number;
  status: string;
  premiered: string;
}

**Comment by eddavidson** [comment]
That’s good to know but should I be able to import my list from pastebin?

**Comment by JumBay** [comment]
You should but your list is not a valid JSON content. 
Checks this https://jsonformatter.org/

**Comment by eddavidson** [comment]
Thank you. I’ll give it a go later.

**Comment by eddavidson** [comment]
Hi there,

Ive copied your player format into my pastbin and it still can't be
downloaded.
Am i missing something?

https://pastebin.com/raw/kT3RP2tF

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by JumBay** [comment]
It works, sometimes there is a cache for pastebin link, means it returns the old content. You can bypass this by adding to your URL `?x` and you increment `x` each time: `https://pastebin.com/raw/kT3RP2tF?1`
