### ISSUE TITLE
[BUG] Inconsistent "next" with wako playlists

### ISSUE THREAD

**Issue by cojoMan** [wako-app/wako#43]
For a show, I have added a list of 10 episodes of season1 let's say, to the wako playlist. Now there is a very neat "one-entry" on the resume tab in the home section for the whole season, with all 10 of those episodes instead of 10 separate ones. Very cool. Sending this to kodi starts the first episode just fine.
But using "next" to get the next episode (wako remote, or kodi interfece) is not working properly :

**Kodi** - if I press the "next" arrow in kodi, the next episode starts just fine, but in the wako app the remote displays the info as for the last episode in that list. And on the resume tab it seems the same, like it jumped from episode 1 to the last one, though the correct episode 2 is playing. 
**Wako** - if I am on an episode that is playing and similarly I press the "next" button on the remote, same thing as above happens, the "next" is being interpreted as the last episode in that list and that one starts playing. 

Tried a few shows to check and it seems like it's consistent behaviour.

**Comment by JumBay** [comment]
Fixed in version 5.1.0
