### ISSUE TITLE
[Feature Request] Send "info" to Kodi

### ISSUE THREAD

**Issue by cojoMan** [wako-app/wako#44]
When playing an episode from my local library, plex managed etc, in Kodi, when you press the info button in the player you get a nice poster and the scrapped synopsis of whatever you are watching, media info like resolution, audio details, the works.
I was wondering, since the remote displays a poster, and as you are going into a show/movie you already have their info to start with, can that be passed along as well to the kodihost so it can be displayed ?

**Comment by JumBay** [comment]
Unfortunately that's not something possible with Kodi's API
