### ISSUE TITLE
REQUEST: add cached TV show pack to cloud

### ISSUE THREAD

**Issue by chiefkes** [wako-app/wako#46]
Would be great as this would allow users to add a season pack to their premiumize cloud and then play subsequent episodes instantly with the premiumizer addon or similar

**Comment by JumBay** [comment]
Same as #45?

**Comment by chiefkes** [comment]
Pretty much, except I’m also requesting the option to add cached tv packs as well as uncached tv packs

**Comment by ryadre** [comment]
I came here to ask similar question - if I find a show or season pack that is cached already in PM, I would like the option like when its not cached - to be able to add it to my own PM cloud storage.

**Comment by lukehansford** [comment]
Be good is we could add them to real Debrid too.

**Comment by JumBay** [comment]
This is not wako related anymore but Helios. See https://github.com/wako-unofficial-addons/helios/issues/1
