### ISSUE TITLE
REQUEST: Default lists in My TV Shows & To Watch

### ISSUE THREAD

**Issue by icpryde** [wako-app/wako#49]
I see a few requests people wanting more control being able to add a show to their custom/person lists. I absolutely want this but it would also be nice if we could change the default "My TV Shows" section and the "To Watch" section. Right now it looks for your Movie watchlist and TV show collection but would be cool if you could change it in settings to whatever personal list you have on trakt.

I know you can kinda do this in "explore" section but something that is default would be nice.

**Comment by JumBay** [comment]
This is something I want to do. I want to move all list to `To watch` and leave the explore for searching.

**Comment by icpryde** [comment]
@JumBay Thanks for the reply, that will be perfect. If we can "set it" so it stays on that list so the one we use the most is the "default" when you open and close the app that would be amazing.

**Comment by JumBay** [comment]
done in v3.1.0
