### ISSUE TITLE
[Feature Request] Providers URL

### ISSUE THREAD

**Issue by mrXoo** [wako-app/wako#50]
Hi there,
I was wondering if the providers url that is inputted could be auto checked for any changes and if there are changes to the file that these could be added.
This would enable me to update my list and then have the app automatically sync with it.

**Comment by JumBay** [comment]
Hello,
What providers are you talking about?

**Comment by mrXoo** [comment]
In order to get anything to actually play you need a providers URL. I have created my own providers URL but if I change it the changes are not added unless I manually install the provider URL. Is there a way a provider URL can be checked at startup?

**Comment by JumBay** [comment]
There is no provider in wako. You may have installed an add-on, you have to contact their support
