### ISSUE TITLE
Autodetect Kodi ip on startup so users don't have to configure their router 

### ISSUE THREAD

**Issue by djay** [wako-app/wako#54]
So can resolve Kodi hosts like osmc.local or use service discovery to not have to type a hostname at all.

**Comment by JumBay** [comment]
With auto-detection, it doesn't find your host?

**Comment by djay** [comment]
@jumbay it doesnt but if it did, I still don't think I want to have to readd each time my router changes assigned DHCP. If I use osmc.local and if the resolve call checks for SD then it would always work. https://www.dodgycoder.net/2015/02/setting-up-bonjourzeroconfmdnsnsd.html?m=1

**Comment by JumBay** [comment]
If the auto-detection doesn't work means there is something with your host that blocks it. Using a hostname instead of the IP address works perfectly at least on iOS (didn't try on android yet). The only thing here I see I could improve is to save the hostname instead of the IP when saving a host from auto-detection.

**Comment by djay** [comment]
mDNS is built into IOS resolve so you need to nothing to make .local
addresses work.

That's not the case with Android unfortunalty. Please have a look at the
documentation I sent.

**Comment by djay** [comment]
I think another way to frame this is to run autodetection run on every startup and try to find the same host. 
Most people don't know how to configure their router to put Kodi on a static ip

**Comment by JumBay** [comment]
This is already integrated.

**Comment by tjamieg** [comment]
> This is already integrated.

This can actually be really annoying if you have multiple kodi setups on the same network... one minute the host is configured correctly with the right IP address and the next minute it autodetects the host details from a different room in the house and starts controlling a different set up

**Comment by JumBay** [comment]
No because it uses the Kodi uuid to set a new IP. If the uuid is not defined, depending on your box or Kodi version, it will use your Kodi name

**Comment by djay** [comment]
Works like a charm. Now it's much easier to recommend to my friends who don't know how to set reserved ip address on their routers. Thanks.
