### ISSUE TITLE
Android 6 latest update force closes when signed in to trakt

### ISSUE THREAD

**Issue by henryjfry** [wako-app/wako#55]
As per the title when I open the app after having updated to the latest version (3.1.2) on my old Galaxy S5 on Android 6 the app starts to load my trakt list and then closes itself.

Signing out of trakt, the app will open and stay open. I've tried clearing the cache and signing back on to trackt but this doesn't resolve the app closing itself.

**Comment by JumBay** [comment]
Could you try the beta 3.1.3 https://play.google.com/apps/testing/app.wako

**Comment by henryjfry** [comment]
I tried the beta on the S5 and it still closes itself when I'm signed into trakt.
With trakt signed out the app appears to work ok.

**Comment by JumBay** [comment]
I’ve published version 3.1.4. I don’t say it’s gonna fix the issue but it could. So if you can give a try.

**Comment by henryjfry** [comment]
Ok I'll try it tonight on the old s5

**Comment by henryjfry** [comment]
I've tried the new version on my Samsung galaxy S5 and it's still force closing when I'm signed into trakt

**Comment by JumBay** [comment]
Sorry since I cannot reproduce, it's hard to debug. Could you try something, go to settings (in wako) > disable all notification and try to log in to trakt again

**Comment by henryjfry** [comment]
The very newest version (3.2.0) with notifications disabled (in the app and in android 6) and with trakt signed in and the cache cleared appears to be working now on my Samsung Galaxy S5 running android 6.
Thanks for looking into this.

**Comment by JumBay** [comment]
Does it work with notification enabled?

**Comment by henryjfry** [comment]
Trying the new version released today with the app notifications turned on in the app and in android settings it is now working.

**Comment by henryjfry** [comment]
Actually I think the issue might be with my trakt up next list.
If I sign out of trakt and clear the cache when I sign back in it will then attempt to cache my data.
While it's doing this it will crash a couple of times but if I keep reopening it, the full list eventually loads.

It does seem more likely to crash with notifications enabled but I have a lot of stuff in my collection and a large up next list as a result.
I wouldn't be surprised if that was causing issues on its own without the possibility of one or two problematic shows (bad characters maybe?)

I'll can try and help you narrow the problem down but if it's irreproducible from your end that could be why?

**Comment by JumBay** [comment]
Another user reported the same issue on android 6. It starts crashing for him when there are 60+ up next episodes. 
It’s something I have to investigate.
