### ISSUE TITLE
[BUG] Restore Purchase not working 

### ISSUE THREAD

**Issue by Gamepsyched** [wako-app/wako#55]
Hi,

i purchased premium on an iPhone but when I deleted and reinstalled the app. Clicking on restore purchase, the app restarts without it being restored.

I have already tried reinstalling the app and clearing the cache, restarting the phone etc.

Thanks for your help,
Lukas

**Comment by JumBay** [comment]
Hi,
Are you logged in to trakt?

**Comment by Gamepsyched** [comment]
Hi,

that did the trick. Thanks for the quick help!

**Comment by JumBay** [comment]
Great.
