### ISSUE TITLE
Still getting ads after purchasing premium membership 

### ISSUE THREAD

**Issue by eengert** [wako-app/wako#57]
I purchased premium on my iPhone and no ads display there. But on my iPad signed into same Apple account, I still get ads after restoring purchases. I can see the green check e subscription under manage membership. I’ve killed and relaunched the app with no success.

**Comment by JumBay** [comment]
Hi,
Are you logged in to trakt/simkl on your iPad?

**Comment by eengert** [comment]
Yes I’m logged into the same Trakt account on both devices.

**Comment by JumBay** [comment]
Could you send me your wako user id to wakoapplication@gmail.com plz

**Comment by eengert** [comment]
Looks like it’s working now. No ads. Thanks.

-- 
Eric Engert
