### ISSUE TITLE
Add player support other than VLC

### ISSUE THREAD

**Issue by hardcod3dd** [wako-app/wako#58]
VLC is great but cant play HDR content. I have tried nplayer and it was able to play HDR content. But the issue is that when i press three dots there is no option to open with other players. I can copy paste the link but the link has the filename before URL so i can only export it as text,then remove that part and add to nplayer.

**Comment by JumBay** [comment]
I don't know what're the three dots, maybe you're referring an option in a third party add-on, in that case contact their support, otherwise in the file explorer settings, you can choose the options to open the video with and nplayer is one the options available for iOS
