### ISSUE TITLE
Subtitle player enhancements

### ISSUE THREAD

**Issue by tele-grams** [wako-app/wako#58]
For subtitles can you also add:
1) Offset keys in the player remote with + and - in the player

For loading subtitles, if you can add drop down options like this:
1. First option takes (copies/paste by wako into search if this option is selected) file name by default in the prompt
2. TMDB name (copies/paste tmdb/trakt name by wako into search if this option is selected)
3. Movie/custom name which can be typed/pasted by user (if selected user can type)
and user can download the sub file

First two option helps typing easy. I have seen lot of sub file names on opensub are same as the media file except it's a sub file.

For me I have seen for > 85% of time auto sub in Kodi will help select based on the file name and these 85% of time no need of sub offset as well, but 15% of the time need to type and sub offset is needed in those cases. 

The above additions would help a lot while playing and loading subs

**Comment by JumBay** [comment]
I've published an update on subtitles 

Unfortunately, I didn't manage to found a way on how to change subtitles offset from kodi's API

I've added an option to paste video filename, it won't be how you wanted because I may not have all these data
