### ISSUE TITLE
filter/disable items that can't be played by device

### ISSUE THREAD

**Issue by djay** [wako-app/wako#61]
My RP2 can't play 10bit HEVC content and neither can my chromecast 2nd gen. At the moment there is a lot of clicks trying different links to get one that works. Other apps warn before playing or filter the list.
What would be nice is if I can select my method of play first globally and then the list will filter accordingly based on knowledge about device/player method and the file/media/link in question. 
e.g. 
- click top right icon similar to cast
- pick from play "kodi via saren", "share url", "play on VLC" (ie combined list of all plugins)
- find show and click play (maybe long press to pick other play method)
- settings for each method determine what to options to show (or mark as unplayable0. ie VLC transcodes so would support all. Share URL might be set to avoid 5.1 and HEVC. Kodi might be set to not handle 5.1 or HEVC. If casting was supported directly then apis can tell you what the device supports.
- picking the next show uses same method of play (less clicks)

**Comment by JumBay** [comment]
Thanks for the issue, but this is related to Helios add-on, could you please open it on its github: https://github.com/wako-unofficial-addons/helios

**Comment by djay** [comment]
I'll rewrite it to show it's not just related to that plugin
