### ISSUE TITLE
REQUEST: one click play by preselecting plugin play method

### ISSUE THREAD

**Issue by djay** [wako-app/wako#63]
Since I'm often playing multiple items on the same device using the same plugin method it would be nice if I could select the play method globally before I click on an item to play. This is similar to how clicking "cast" on other apps will keep playing on the same selected device for the next items played until disconnected.
This would avoid having to click once to view the item page and again to pick the method of play (or 3 times for some plugins).
If a plugin uses "share via" it would be even nicer if the app shared to could also be pre-picked to "cast" to.

**Comment by JumBay** [comment]
wako doesn't handle any play method, it's all done on add-ons side. Nothing can be done here. You have to create an issue on their github.

**Comment by djay** [comment]
I'm suggesting you improve the UI by changing how plugins work so they advertise their play methods so the UI can preselect one before click on an item. 
This is a plugin archtecture change not a specific plugin change.
Can you reopen it please @JumBay ?

**Comment by JumBay** [comment]
Yes but plugins could do anything, not only playing stuff... So I don't see any easy way how to manage this and make it simple for the end-user

**Comment by djay** [comment]
In addition to defining visual components on the details page they could
optionally define a list of play actions. Maybe in the manifest or maybe
dynamically via an API call.

Each call method has a name that appears on a cast/"play using" menu in the
top right corner on every screen.
When episode is opened then instead of the details page the method is
called on the plug-in and it does whatever it wants.

**Comment by djay** [comment]
@JumBay still not clear?

**Comment by JumBay** [comment]
Something I don't understand. 
- From the Next Up feature OR any list, you click on an episode/movie, what happens? You don't navigate to the item detail but this will execute the add-on auto-action?

**Comment by djay** [comment]
@JumBay exactly. Basically a way to avoid picking the plugin and play method every time I click on an episode or movie. Similar to how the "cast" button works in the youtube app. I don't pick where to cast it for each youtube video I want to play but instead pick the cast device once for all plays going forward until I click it again and pick disconnect or pick another device/method.
Actually you could also make it that it navigations to the item detail and does the play method automatically after which is more how youtube works. Looking at the netflix apps I notice that their home is a mix of items that play automatically (continue watching) and other lists that don't, which is an interesting idea. but either way if I've picked another method to play such as casting to my chromecast, then it "sticks" and I don't have to keep picking it (at least until the app session is over).

I also realise "cast" is not the same concept is the various options the plugins can give... but its close. 
Today I want to play on kodi, tomorrow I am in the bedroom and want to play on my chromecast via VLC, mon I'm at the office and want to play locally via some other app.

I realise it's a change to the plugin api since apis need to expose the names of their play methods to the main app but "one click play" is such a nice user experience.

I think if the plugin api was such that at the point you clicked the global "cast'/"play via" button in the top right, you call each plugin in turn and they can dynamically return possible play methods. This would allow for example an android cast plugin that returned a list of devices. Or the kodi select plugin can return a list of kodis it discovers at that point. In addition I notice apps like bubbleupnp create directshare targets on android for renders (like a chromecast device). What would be really nice is if the share actions selected ended up in the in the list of play methods returned by the plugin. Looking at the api it seems like thats possible, at least once a share as happened once (https://developer.android.com/reference/android/widget/ShareActionProvider.html#setOnShareTargetSelectedListener(android.widget.ShareActionProvider.OnShareTargetSelectedListener)). So in this case you could imagine I would click this global "cast"/"play with" button and in that list I'd have the option "BubbleUPNP (chromecast bedroom)" making it even more "one click play".
