### ISSUE TITLE
Wako not showing install third party sources option

### ISSUE THREAD

**Issue by yoyo617** [wako-app/wako#69]
I have linked my trakt account and got premium. Im the latest ios update on iphone. The option for installing third party sources is not showing up for me.

**Comment by Havelod** [comment]
I have the same issue

**Comment by 3nesb4by** [comment]
same issue, someone said it shows up after 24 hours. I am still waiting, I paid just for this feature specific

**Comment by JumBay** [comment]
Hi, it's been fixed, open wako, go to settings then clear cache, restart the app.
