### ISSUE TITLE
Empty space endless scrolling everywhere

### ISSUE THREAD

**Issue by Sovilor** [wako-app/wako#71]
Android 12
MIUI Global 13.0.1
App Version 6.0.3 (build: 2022-08-10)-34/34

Endless empty space, endless scrolling everywhere, very annoying bug.
![IMG_20221001](https://user-images.githubusercontent.com/48744665/193430366-0e0d1bb6-f333-40df-a516-16ada4d96ad2.jpg)

https://user-images.githubusercontent.com/48744665/193430367-7e468a90-b4f2-49f4-a781-be6fcc6361d7.mp4

**Comment by JumBay** [comment]
Could you check build `2022-10-03`

**Comment by Sovilor** [comment]
> Could you check build `2022-10-03`

No update in Play Store.

**Comment by Sovilor** [comment]
Fixed in the latest update.
