### ISSUE TITLE
Request: add option to download to nPlayer via Helios add on

### ISSUE THREAD

**Issue by urWorthIT** [wako-app/wako#72]
When viewing a list of sources you get an option to download to VLC, it would be great if this option was available to allow a user to download to nPlayer. 

Default action could place it directly in the default folder for nPlayer. 

Secondary action could be to allow a user to define what folder, create new, to download file to.

**Comment by JumBay** [comment]
Plz recreate your issue on  [Helios](https://github.com/wako-unofficial-addons/helios/issues) repository
