### ISSUE TITLE
APi error trakt

### ISSUE THREAD

**Issue by Addzk72** [wako-app/wako#72]
Why does it keep flashing up at top of screen saying trakt api error?

**Comment by ryhoo2** [comment]
I got the same problem since the recent update from Google Play Store. The message says: "Trakt API - the server is overloaded. Try again in 30 seconds."

**Comment by JumBay** [comment]
https://trakt.tv/

**Comment by JumBay** [comment]
I recommend you to switch to simkl

**Comment by ryhoo2** [comment]
I found a comment on their Twitter:

On Dec 11 at 7:30 PST, our main database crashed & corrupted some of the data. This is unplanned & we've been working around the clock to restore it. It's a painstakingly slow process given the scale of data. We unfortunately have no ETA but we're doing everything we can.

**Comment by ryhoo2** [comment]
I have a lifetimepremium license that is connect to my Trakt account, so switching to simkl is not an option for me.

**Comment by JumBay** [comment]
You can check this https://www.reddit.com/r/wako/comments/zlzs62/trakt_is_down_use_simkl_instead/
