### ISSUE TITLE
Unable to install any third party addons on iOS

### ISSUE THREAD

**Issue by Brandonmuk** [wako-app/wako#73]
Latest iOS update broke something. Now it seems to be impossible to install third party addons

**Comment by JumBay** [comment]
what's the error?

**Comment by Brandonmuk** [comment]
> what's the error?

I enabled logs and unfortunately no error gets returned. Once the url manifest address gets entered and "OK" is selected nothing happens

**Comment by JumBay** [comment]
If you try to install this demo add-on does it work?
`https://raw.githubusercontent.com/wako-app/addon-starter-kit/main/dist/manifest.json`

**Comment by icpryde** [comment]
@JumBay the demo plug-in worked for me, but I was also unable to install helios i've tried so many times it just will not install.

BUT this one you linked here did work! 

I'm on iOS 16.2 and on iPhone 14 Pro

**Comment by Brandonmuk** [comment]
> @JumBay the demo plug-in worked for me, but I was also unable to install helios i've tried so many times it just will not install.
> 
> BUT this one you linked here did work! 
> 
> I'm on iOS 16.2 and on iPhone 14 Pro
> 
> Heres a video of me trying as well
> 
> https://user-images.githubusercontent.com/29389746/209250338-08d39e8b-34ad-4821-9782-7fce2d0df99b.MP4
> 
> 

https://raw.githubusercontent.com/wako-unofficial-addons/helios/master/dist/manifest.json

Try that and see if it works.

**Comment by Brandonmuk** [comment]
> If you try to install this demo add-on does it work?
> `https://raw.githubusercontent.com/wako-app/addon-starter-kit/main/dist/manifest.json`

You were right. Thanks for doing what you do.

**Comment by icpryde** [comment]
@Brandonmuk oh wow thank you!!!! That worked

**Comment by JumBay** [comment]
Error message has been added if the URL is not a valid manifest

**Comment by icpryde** [comment]
@Brandonmuk do you have a copy of the nomo one as well? Can’t find that link anywhere
