### ISSUE TITLE
Request: Unlink Kodi volume from device volume

### ISSUE THREAD

**Issue by GeneralBison** [wako-app/wako#73]
Can an option be added to disable this feature? 
It causes some really strange behaviour with fluctuating volume and makes using the device while watching Kodi practically impossible!

**Comment by JumBay** [comment]
There is already a setting option for this in Settings > Kodi.   
Moreover, this feature has been removed for android (latest OTA update) as the controls are different from iOS.

**Comment by GeneralBison** [comment]
Apologies, it only started happening today and I thought it was a new feature, didn't think it'd be under the Kodi host selector.
