### ISSUE TITLE
Alldebrid

### ISSUE THREAD

**Issue by grhack** [wako-app/wako#74]
Add Alldebrid support

**Comment by JumBay** [comment]
Plz recreate your issue on  [Helios](https://github.com/wako-unofficial-addons/helios/issues) repository

**Comment by grhack** [comment]
I have Real Debrid configured. If there is an option to configure Alldebrid I don’t see it? I am having issues with Real Debrid is why I was asking.

**Comment by JumBay** [comment]
I understand your issue but this concerns Helios addon, not wako. If you want all debrid being added to Helios ask on its GitHub
