### ISSUE TITLE
iOS update 16.1.2 broke Wako

### ISSUE THREAD

**Issue by giandre** [wako-app/wako#75]
Hi,
I updated my iPhone to 16.1.2 and wako started to crash and I could not open it anymore so I decided to uninstall and reinstall the app. Now, I can’t restore my subscription. The app flashes and then revers to the “free” version. Do you have any tips to resolve the issue?

**Comment by JumBay** [comment]
Hi,
Are you connected to your trakt account?
If so please contact us at wakoapplication@gmail.com with your user Id

**Comment by giandre** [comment]
Hi!
First, thanks for the quick response. That was it! I was able to restore it correctly.
I appreciate the help!
Gio
