### ISSUE TITLE
TV shows not loading even though i switched it to simkl with trakt down

### ISSUE THREAD

**Issue by Aeneax** [wako-app/wako#76]
So with trakt down movies and tv shows weren't loading. I switched to simkl and movies started loading again, but tv shows are still not loading. And it sill shows the notification trakt api error even though I already logged out.

**Comment by JumBay** [comment]
Lots of informations are pulled out from trakt api, since it's down it affects the app. I'll check to get data from other api

**Comment by JumBay** [comment]
An update has been pushed to be less trakt dependant. You may still encounter trakt error message but it should globally work
