### ISSUE TITLE
I have Wako tv iOS working fine on one phone not other

### ISSUE THREAD

**Issue by lynnyskynny** [wako-app/wako#79]
I have wako tv running perfectly using real debrid and a 3rd party app on the first iphone with premium version of wako tv using Trekt. On my second iPhone it is logged into the same trekt account however it tells my it’s not a premium account. It’s supposed to do multiple devices with same premium login

**Comment by JumBay** [comment]
Trakt had some issue, and their api is just back online. I recommend that you logout from your account and login back. If you need to in wako > settings > membership click the restore purchases button

**Comment by lynnyskynny** [comment]
Right I knew that and have don’t that multiple times. It shows the same account names but one says premium and the other says not. Maybe I’ll try logging in to it with Simkl?

**Comment by JumBay** [comment]
no you don't need too, you only have to be connected to the same wako's account. 
Did you logout first and login back to test?
You can send an email at wakoapplication@gmail.com or dm on reddit with your wako user id. I will check what's going on
