### ISSUE TITLE
Bug: Episode progress not always syncing

### ISSUE THREAD

**Issue by Crapy** [wako-app/wako#79]
I sometimes finish watching an episode yet it says I only watched half of it on Resume.

You should perform a check when entering the app (and it refreshes on trakt api) that if an episode is marked as watched to check if it is in Resume, if it is, remove it.

**Comment by JumBay** [comment]
Do you still encounter this issue?

**Comment by Crapy** [comment]
> Do you still encounter this issue?

Yup, may be cause of Android battery saving, but I did all the steps needed for it to always be on, still nothing and when I remove optimizion I lose battery as fast as playing a very demanding game just from the wako app being on the background

**Comment by JumBay** [comment]
Shouldn't be an issue anymore?
