### ISSUE TITLE
Only show chromecast devices if no kodi setup or added in the resume tab

### ISSUE THREAD

**Issue by oathzed** [wako-app/wako#8]
It shows Kodi as an option but I don't have kodi setup at all and its not an option I have setup. Can you just show the castable devices when only cast is setup

https://imgur.com/a/tydTDXt

Edit: same issue in the file explorer tab

**Comment by JumBay** [comment]
Did you try to disable Kodi from the list in settings > file explorer > configure

**Comment by oathzed** [comment]
> Did you try to disable Kodi from the list in settings > file explorer > configure

Now I feel like an idiot lol. That fixed everything for me. Thanks! I'll close this
