### ISSUE TITLE
Mark as watched not working for TV shows

### ISSUE THREAD

**Issue by Minefield247** [wako-app/wako#80]
Eye turns blue, but when I return to the TV show page it's back to being white. No change to trakt dashboard. Add to watchlist doesn't work either. I'm pretty sure it to do with the changes that were made the other day to use simkl more during the traktapocalypse.
Movies work fine, mark as watched and add to watchlist.
Thanks.

**Comment by Minefield247** [comment]
So I've done some more research.

If I swipe left from the home screen and click the eye, it doesn't work.

If I select the episode from the home screen then select the eye it works.

If I select 'view show' from the episode screen, then select the eye it doesn't work. In fact that show screen doesn't show any watched data at all, and shows the simkl rating.

**Comment by JumBay** [comment]
Check build 2022-12-21, it should fixes it

**Comment by Minefield247** [comment]
Thanks, that seems to have solved it. I'll let you know if I come across any other issues.
