### ISSUE TITLE
REQUEST: Merge the Resume and Watch Next Tabs

### ISSUE THREAD

**Issue by MadMax96xaMdaM** [wako-app/wako#82]
I would suggest that they are then split into two tabs, one for movies and one for shows and anime where when you click one the episode/movie you get options to resume and where it will resume to (if applicable) or start over and then it should ask how you want to play (VLC, open with, Kodi and which host after, etc).

I think MX Player and VLC have APIs for padding on watched statues and where to resume.

**Comment by JumBay** [comment]
It's not something that will be done for now, I'm closing it
