### ISSUE TITLE
I bought a subscription!!

### ISSUE THREAD

**Issue by Jleep2017** [wako-app/wako#84]
I bought a subscription on iOS. I downloaded the app on Andriid signed into Trakt. It is not syncing with my android app. I hit restore purchase and nothing happens on android. I can't even restore it because it says it's for premium users only. But on IOS it says I'm a premium user!!. How long does it take for the android to accept me being premium?

**Comment by JumBay** [comment]
If you're using the same wako account on both devices please send me a screenshot of the membership page from both your iOS and Android device at wakoapplication@gmail.com

**Comment by Jleep2017** [comment]
I logged out and logged back into both and they upgraded.

**Comment by JumBay** [comment]
Great
