### ISSUE TITLE
BUG: Screen skipping while scrolling on large Android screens

### ISSUE THREAD

**Issue by ctjameson** [wako-app/wako#85]
The posters jump about 100 pixels randomly while scrolling on android large form factor screens. 

Device: Galaxy Tab A 10.5" 2018
Android: 9.0
Wako version: 3.5.3 (build 2019-11-12)

**Comment by JumBay** [comment]
Could you send me a video of this plz.

**Comment by ctjameson** [comment]
https://drive.google.com/file/d/1-gry8hYa3hgBEIAqNLRvdfKQenMd9Tcb/view?usp=drivesdk

There ya go! If you want me to test any kind of settings on the tab, let me
know!

**Comment by JumBay** [comment]
The latest OTA update should fix this, could you confirm me this?

**Comment by ctjameson** [comment]
Will do. I’ll check it when I get home tonight. Thanks JBM!

**Comment by ctjameson** [comment]
Butter smooth and way easier to use on the large screen! Thanks!

**Comment by JumBay** [comment]
Perfect
