### ISSUE TITLE
Change username

### ISSUE THREAD

**Issue by Lxxrxns** [wako-app/wako#90]
Hi there,

I am a legacy lifetime premium user. The premium account is linked to my trakt account. On trakt, i recently changed my display name, however, the name in wako is still my old name, even when disconnecting and reconnecting. Is there a way for me to change the display name of my wako account?

Thanks!

Laurens

**Comment by JumBay** [comment]
Hi,

You're referring the user name displayed on the home page or the one present in your wako's id?

**Comment by Lxxrxns** [comment]
Yeah on the Home page

**Comment by JumBay** [comment]
Ok that's weird, just tried it without any issue. Could you send me your wako ID at wakoapplication@gmail.com

**Comment by JumBay** [comment]
This has been fixed
