### ISSUE TITLE
Constant Crashing since recent real debrid outtage

### ISSUE THREAD

**Issue by JosephmUH** [wako-app/wako#93]
Hi,
Wako keeps crashing upon launch after the recent RealDebrid outage. 

iPhone 12 Pro iOS 16.5

**Comment by JosephmUH** [comment]
After further testing, I can get into the app once in Airplane mode. After, I see API errors at the top related to CRUD/Real Debrid

**Comment by JumBay** [comment]
Hi,
Sorry for the issue, wako doesn't call real debrid, this has to do with an add-on installed. You should try to uninstall it and see what's going on. In the meantime I'll check why api calls crash the app.

**Comment by JosephmUH** [comment]
Very true, likely an issue with Helios then. I’ll remove my issue from GitHub.Thank you!!! On Jul 14, 2023, at 2:22 AM, Jean-Baptiste Malatrasi ***@***.***> wrote:﻿
Hi,
Sorry for the issue, wako doesn't call real debrid, this has to do with an add-on installed. You should try to uninstall it and see what's going on. In the meantime I'll check why api calls crash the app.
