### ISSUE TITLE
enable subtitles not working

### ISSUE THREAD

**Issue by SamJongenelen** [wako-app/wako#96]
Hey, I think I have a bug? 

When I use the enable subtitles toggle (during playback), subtitles are not enabled. But the toggle remains on on the app.
When I use the Kodi player interface to do it they are enabled.

Using Android10 as remote with Kodi leya on Shield

**Comment by JumBay** [comment]
The toggle displays what kodi's API returns, that means if it's enabled, then kodi's API returns that subtitles are enabled.  
Whenever you've got this issue, could you try to restart wako and see if the toggle remains enabled?

**Comment by SamJongenelen** [comment]
The toggle does not stay enabled after restarting the app.

So it would seem the enabled subtitles command isn't sent / received properly.

Can you reproduce the issue at all?

**Comment by JumBay** [comment]
No, I don't have this issue.
Do other commands failed as well as subtitles offset... ?

**Comment by SamJongenelen** [comment]
Ok, i reset my Kodi build and re-added host in wako. Now the problem has disappeared 👍
