### ISSUE TITLE
REQ: filter for completed/watched in the movie section

### ISSUE THREAD

**Issue by emiel1234** [wako-app/wako#97]
Hi,

First of all thanks for this great app.
What I would like to see is a filter option for completed/watched movies.
It comes from Trakt ofcourse and I can see on Trakt and in the app by the icon that they are watched.

But there is no way to filter them out to see only the ones which I haven’t watched. It is getting a big list now and I basicly have to scroll everything to find the ones I didn’t watched.

Thanks in advance,
Emiel

**Comment by JumBay** [comment]
On the filter menu in movies section, there is such an option, but this doesn't work for custom lists only for trakt's lists like Popular, Trending... Can you confirm that's what you want? I'll make it works for all lists in the explore tab

**Comment by emiel1234** [comment]
Well it is a Trakt list.

Euhm I use Trakt trhoug there website and select “add to collection”. So
far so good, it shows up in the wako app also. And it shows withe the
little icon if I have viewed them before also. But there is no option in
the filter menu to lock them out?

With series/shows  it works ok, I do that the same way. But that works a
little different because of next to view etc.

Not sure if I explain this entirely correct btw.
Please just ask.

Thanks

Op di 17 dec. 2019 om 08:38 schreef Jean-Baptiste Malatrasi <
notifications@github.com>

**Comment by emiel1234** [comment]
Ok so now I see the filter and it’s working also.
Either I have overlooked it or it’s just installed. Anyway doesn’t matter
it is working now.

Thanks anyway and keep going, great app

Greetings Emiel

Op wo 18 dec. 2019 om 06:42 schreef Emiel Minnee <emielminnee@gmail.com>
