### ISSUE TITLE
Unresponsive addon buttons 

### ISSUE THREAD

**Issue by dblviking** [wako-app/wako#98]
App version 3.6.2 iOS 13 and iPadOS 13

The MovieDB addon, imdb addon and popular 3rd party addon buttons don’t do anything. I’m not sure what today’s update did, but it certainly broke something.

**Comment by JumBay** [comment]
Do you have any subscription? If not do you see ads on click?

**Comment by dblviking** [comment]
> Do you have any subscription? If not do you see ads on click?

I do not see ads. I think it might be due to my pihole.

**Comment by dblviking** [comment]
I disabled my ad blocker and now I see the two ads but when I hit Play on Kodi, kodi shows a progress circle but just stops. Nothing plays.

**Comment by JumBay** [comment]
This concerns a third party addon, see with its developer
